web:
  welcome: <h1><font face='verdana'>Spring boot rocks! Local profile</font></h1>

spring:
  kafka:
    topic:
      name: topicName
    bootstrapAddress: localhost:9092
    group-id: server.broadcast