web:
  welcome: <h1><font face='verdana'>Spring boot rocks! Local profile</font></h1>

spring:
  kafka:
    topic:
      name: topicName
    bootstrapAddress: localhost:9092
    group-id: server.broadcast
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
          auto-create-topics: true
      bindings:
        string-request:
          binder: kafka
          destination: kafkaStream
        string-response:
          binder: kafka
          destination: kafkaStream