#PORT
server:
  port: 8080

#LOGGER
logging:
  level:
    root: INFO
    my.project.home.analyzer: DEBUG

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
